name: Update Website Content

on:
  push:
    paths:
      - 'website/**'  # Only trigger when files in website/ change
    branches:
      - main

jobs:
  update-configmap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
      
      - name: Generate ConfigMap from website files
        run: |
          kubectl create configmap apache-cm0 \
            --from-file=website/ \
            --namespace=default \
            --dry-run=client -o yaml > apache-configmap.yaml
      
      - name: Apply ConfigMap
        run: |
          kubectl apply -f apache-configmap.yaml
      
      - name: Restart Apache deployment
        run: |
          kubectl rollout restart deployment apache -n default
          kubectl rollout status deployment apache -n default --timeout=2m
      
      - name: Commit generated ConfigMap (optional)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add apache-configmap.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update ConfigMap from website changes" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
